### ISSUE TITLE
Reporter.py needs to be updated when using bokeh 3.0.2

### ISSUE THREAD

**Issue by raymerta** [wangvsa/recorder-viz#3]
It seems that bokeh 3.0.2 changes several parameters and it breaks the recorder-viz 0.4.5 in several places. 

- when using `figure`, `plot_width` and `plot_height` needs to be changed to `min_width` and `min_height`
- the x-axis that is using `range` needs to be converted with `list(range(...)` 
- in `gridplot`, `plot_width` and `plot_height` needs to be changed to `width` and `height`

The visualization works correctly after this changes

**Comment by wangvsa** [comment]
Hi Radita, thanks for giving it a try. Strange why bokeh doesn't make it backward-compatible. I will try to see if I can make it work for both versions of bokeh.

**Comment by wangvsa** [comment]
Fixed.
